package uk.org.landeg.projecteuler.problems;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import uk.org.landeg.projecteuler.ProblemDescription;

@Order(45)
@Component
public class Problem045 implements ProblemDescription<Long>{
	private static final Logger LOG = LoggerFactory.getLogger(Problem045.class);
	@Override
	public String getTask() {
		return "Find the next triangle number that is also pentagonal and hexagonal";
	}

	@Override
	public String getDescribtion() {
		return "Triangle, pentagonal, and hexagonal numbers are generated by the following formulae : It can be verified that T285 = P165 = H143 = 40755";
	}

	@Override
	public Long solve() {
		long np = 160, nh = 140;
		long p = 0, h = 0;
		do {
			if (p == 0 || p == 1 || p < h) {
				np++;
				p = np * (3 * np - 1) / 2;	
			}
			if (h == 0 || h == 1 || h < p) {
				nh++;
				h = nh * (2 * nh - 1);
			}
			if (h == p) {
				LOG.info("Discovered equality np={} nh={} h={}", np, nh, h);
				if (h > 40755) {
					LOG.info("h exceeds 40755 ({})", h);
					break;
				}
				p=0;
			}
		} while (p != h || p <= 40755);
		LOG.info("Escacpe conditions, p {} h {}", p, h);
		return p;
	}

	@FunctionalInterface
	private static interface SequenceOperator {
		public long transform (final int n);
	}
}
